package models

import (
	"time"

	"gorm.io/gorm"
)

// RawData represents raw data fetched from external APIs
type RawData struct {
	gorm.Model
	SourceName string
	Content    string `gorm:"type:text"`
	FetchedAt  time.Time
}

// ProcessedData represents transformed data after processing raw data
type ProcessedData struct {
	gorm.Model
	Content    string `gorm:"type:text"`
	ProcessedAt time.Time
}

// LLMAnalysis represents insights generated by an LLM
type LLMAnalysis struct {
	gorm.Model
	Content     string `gorm:"type:text"`
	GeneratedAt time.Time
}
